export const ARTIFACT_RARITY = {
  COMMON: "COMMON",
  UNCOMMON: "UNCOMMON",
  RARE: "RARE",
  EPIC: "EPIC",
  FABLED: "FABLED",
  MYTHICAL: "MYTHICAL",
  LEGENDARY: "LEGENDARY",
  TRANSCENDENT: "TRANSCENDENT",
};

export const ARTIFACT_AFFIX = {
  ANCIENT_POWER_ALL: "ANCIENT_POWER_ALL",
  IDLE_DPS: "IDLE_DPS",
  CLICK_DAMAGE: "CLICK_DAMAGE",
  OFFLINE_EARNINGS: "OFFLINE_EARNINGS",
  CRIT_CHANCE: "CRIT_CHANCE",
  SHARD_FIND: "SHARD_FIND",
};

export const RARITY_WEIGHTS = {
  COMMON: 0.45,
  UNCOMMON: 0.25,
  RARE: 0.14,
  EPIC: 0.08,
  FABLED: 0.04,
  MYTHICAL: 0.02,
  LEGENDARY: 0.015,
  TRANSCENDENT: 0.005,
};

export const RARITY_MULTIPLIERS = {
  COMMON: 1,
  UNCOMMON: 1.5,
  RARE: 2.5,
  EPIC: 4,
  FABLED: 6,
  MYTHICAL: 9,
  LEGENDARY: 15,
  TRANSCENDENT: 25,
};

// Base Cost Multipliers (for Upgrade)
export const RARITY_BASE_COST = {
  COMMON: 5,
  UNCOMMON: 6,
  RARE: 8,
  EPIC: 10,
  FABLED: 12,
  MYTHICAL: 14,
  LEGENDARY: 18,
  TRANSCENDENT: 26,
};
